# Provide a list of RAxML-NG versions you want to test all the command lines for
# Each list entry consists of two values: an alias for the version and a path to the executable of this version
# Each list entry consists of two values: an alias for the version and a path to the executable of this version
# e.g.:
# - [raxmlng-version-1.1.0, /home/schmidja/software/raxml-ng/bin/raxml-ng]
executables:
  - [raxmlng-version-1.2, ../raxml-ng-v1.2/bin/raxml-ng]
  - [raxmlng-version-1.1, ../raxml-ng-v1.2/bin/raxml-ng, --extra compat-v11]
  - [raxmlng-adaptive, ../raxml-ng-adaptive/bin/raxml-ng-adaptive]

# Provide a list of command lines you want to test
# you do not need to provide the --msa and --model flags, as the pipeline will add them later
# so if you want to run the following command line: raxml-ng --search1 --msa msa.phy --model GTR+G --seed 0 --threads 2
# provide the following: - --search1 --seed 0 --threads 2
commandLines:
  - --threads auto{40} --seed 0 --redo

# Provide a list of MSAs you want to run all commands and versions on
# Each list entry consists of two values: the path to the MSA and the respective model
datasets:
  - [../data_new/101/101.phy, GTR+G]
  - [../data_new/125/125.phy, GTR+G]
  - [../data_new/1288/1288.phy, GTR+G]
  - [../data_new/140/140.phy, LG+G]
  - [../data_new/1481/1481.phy, GTR+G]
  - [../data_new/150/150.phy, GTR+G]
  - [../data_new/1512/1512.phy, GTR+G]
  - [../data_new/1604/1604.phy, GTR+G]
  - [../data_new/1718/1718.phy, GTR+G]
  - [../data_new/1908/1908.phy, GTR+G]
  - [../data_new/2000/2000.phy, GTR+G]
  - [../data_new/218/218.phy, GTR+G]
  - [../data_new/354/354.phy, GTR+G]
  - [../data_new/404/404.phy, GTR+G]
  - [../data_new/479/479.phy, GTR+G]
  - [../data_new/500/500.phy, GTR+G]
  - [../data_new/628/628.phy, GTR+G]
  - [../data_new/714/714.phy, GTR+G]
  - [../data_new/994/994.phy, GTR+G]
  - [../data_new/3782/3782.phy, GTR+G]
  - [../data_new/128/128.phy, GTR+G]
  - [../data_new/2308/2308.phy, GTR+G]
  - [../data_new/2445/2445.phy, GTR+G]
  - [../data_new/2554/2554.phy, GTR+G]
  - [../data_new/4114/4114.phy, GTR+G]
  - [../data_new/94/94.phy, LG+G]
  - [../data_new/59/59.phy, GTR+G]
  - [../data_new/6718/6718.phy, GTR+G]
  - [../data_new/7664/7764.phy, GTR+G]
  - [../data_new/775/775.phy, LG+G]

# Path to an IQ-Tree executable for the statistical tests
iqtree: [/hits/fast/cme/togkou/fastclv-raxml-ng/iqtree-2/iqtree-2.1.2-Linux/bin/iqtree2, -blmin 1e-3]
consel_dir: [/home/togkouas/consel/consel/bin] # path to consel
raxmlng_evaluation_bin: [/home/togkouas/raxml-ng_v1.2.0/raxml-ng, --threads 40]

# where to store all output files
outdir:
  results
